<a href="https://colab.research.google.com/github/egyptai/DecisionTree/blob/main/20210609BaggingIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
import numpy as np
from sklearn.metrics import classification_report

In [2]:
iris = load_iris()

In [3]:
trainX, testX, trainY, testY = train_test_split(iris['data'], iris['target'], test_size = 0.2)

In [5]:
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
dtree = DecisionTreeClassifier(criterion='gini', max_depth=8)
svm = SVC(kernel='rbf', gamma=0.1, C=1.0, probability=True)
lreg = LogisticRegression(max_iter=500)

In [6]:
prob = np.zeros((testY.shape[0], iris.target_names.shape[0]))
base_model = [knn, dtree, svm, lreg]
for m in base_model:
    bag = BaggingClassifier(base_estimator=m, n_estimators=100, bootstrap=True)
    bag.fit(trainX, trainY)
    
    prob += bag.predict_proba(testX)

In [7]:
predY = np.argmax(prob, axis=1)

In [8]:
print('\nConfusion matrix :')
print(confusion_matrix(testY, predY))
print()
print(classification_report(testY, predY, target_names=iris.target_names))


Confusion matrix :
[[ 6  0  0]
 [ 0 13  1]
 [ 0  0 10]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         6
  versicolor       1.00      0.93      0.96        14
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.98      0.97        30
weighted avg       0.97      0.97      0.97        30

